/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Customer;
import domain.DisplayData;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import model.TempTestEmp;
import thesisproject.DistanceCls;

/**
 *
 * @author Shadhin
 */
public class InconsistencyPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaxPanel
     */
    public InconsistencyPanel() {
        initComponents();
//        loadData();
        DistanceCls.call();;
    }
    DefaultTableModel model;
    Object[] row = {};

    public void loadData() {
        DisplayData displayData;
        ArrayList<TempTestEmp> arrayList;
        displayData = new DisplayData();
        arrayList = displayData.getTempTestEmp();
        model = (DefaultTableModel) inconsistencyTable.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
        row = new Object[12];
        for (int i = 0; i < arrayList.size(); i++) {
            row[0] = arrayList.get(i).getId();
            row[1] = arrayList.get(i).getFn();
            row[2] = arrayList.get(i).getLn();
            row[3] = arrayList.get(i).getCc();
            row[4] = arrayList.get(i).getAc();
            row[5] = arrayList.get(i).getPhn();
            row[6] = arrayList.get(i).getStreet();
            row[7] = arrayList.get(i).getCity();
            row[8] = arrayList.get(i).getZip();
            row[9] = arrayList.get(i).getSalary();
            row[10] = arrayList.get(i).getStatus();
            row[11] = arrayList.get(i).getFrequency();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inconsistencyTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ruleLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Experiment: Inconsistency");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        inconsistencyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fn", "ln", "cc", "ac", "phn", "street", "city", "zip", "salary", "status", "frequency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inconsistencyTable.setMaximumSize(new java.awt.Dimension(1260, 600));
        inconsistencyTable.setMinimumSize(new java.awt.Dimension(1260, 600));
        jScrollPane1.setViewportView(inconsistencyTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Rule:");

        ruleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ruleLabel.setForeground(new java.awt.Color(0, 153, 0));
        ruleLabel.setText("--------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1006, Short.MAX_VALUE)
                .addComponent(refreshButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(ruleLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ruleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        ruleLabel.setText("");
        ruleLabel.setText(DistanceCls.errorDetection());
        loadData();
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inconsistencyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel ruleLabel;
    // End of variables declaration//GEN-END:variables
}
