/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Customer;
import model.Tax;
import domain.DisplayData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shadhin
 */
public class TaxPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaxPanel
     */
    public TaxPanel() {
        initComponents();
        //loadData();
    }
    
    DefaultTableModel model;
    Object[] row = {};
    public void loadData() {
        DisplayData displayData;
        ArrayList<Tax> taxList;
        displayData = new DisplayData();
        taxList = displayData.getTax();
        model = (DefaultTableModel) taxTable.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
        row = new Object[16];
        for (int i = 0; i < taxList.size(); i++) {
            row[0] = taxList.get(i).getId();
            //System.out.println("RoW: "+row[0]);
            row[1] = taxList.get(i).getFname();
            row[2] = taxList.get(i).getLname();
            row[3] = taxList.get(i).getGender();
            row[4] = taxList.get(i).getAreaCode();
            row[5] = taxList.get(i).getPhone();
            row[6] = taxList.get(i).getCity();
            row[7] = taxList.get(i).getState();
            row[8] = taxList.get(i).getZip();
            row[9] = taxList.get(i).getMarritalStatus();
            row[10] = taxList.get(i).getChildren();
            row[11] = taxList.get(i).getSalary();
            row[12] = taxList.get(i).getRate();
            row[13] = taxList.get(i).getSingleEx();
            row[14] = taxList.get(i).getMarriedEx();
            row[15] = taxList.get(i).getChildEx();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taxTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tax Data Sheet");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        taxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Gender", "Area Code", "Phone", "City", "State", "Zip", "Marital Status", "Children", "Salary", "Rate", "Single Ex-Emp", "Marital Ex-Emp", "Child  Ex-Emp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        taxTable.setMaximumSize(new java.awt.Dimension(1260, 600));
        jScrollPane1.setViewportView(taxTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refreshButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable taxTable;
    // End of variables declaration//GEN-END:variables
}
